language: php
php:
  - 7.1
  - 7.2
services:
    - memcached
cache:
    directories:
      - "$HOME/.composer/cache"
before_install:
  - sudo apt-get -y install libmemcached-dev
  - pecl channel-update pecl.php.net
  - echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update
  - composer install
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpunit
after_success:
  - bash <(curl -s https://codecov.io/bash)
