language: php
php:
  - 7.1
  - 7.2
services:
    - memcached
    - mysql
cache:
    directories:
      - "$HOME/.composer/cache"
before_install:
  - sudo apt-get -y install libmemcached-dev
  - pecl channel-update pecl.php.net
  - travis_retry composer self-update
  - composer install
  - mysql -e "CREATE USER 'chzapp'@'localhost' IDENTIFIED BY 'chzapp';"
  - mysql -e "CREATE DATABASE chzapp;"
  - mysql -e "GRANT SELECT ON chzapp.* TO 'chzapp'@'localhost';"
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpunit
after_success:
  - bash <(curl -s https://codecov.io/bash)
