build: false
clone_depth: 1
clone_folder: c:\projects\chzapp

services:
  - mysql
  - memcached

cache:
    - '%LOCALAPPDATA%\Composer\files'
    - c:\projects\chzapp\composer.phar

init:
    - SET PATH=c:\php;C:\Program Files\MySQL\MySQL Server 5.7\bin\;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET ANSICON=121x90 (121x90)
    - REG ADD "HKEY_CURRENT_USER\Software\Microsoft\Command Processor" /v DelayedExpansion /t REG_DWORD /d 1 /f

install:
    - mkdir c:\php && cd c:\php
    - appveyor DownloadFile https://raw.githubusercontent.com/symfony/binary-utils/master/cacert.pem
    - appveyor DownloadFile https://github.com/symfony/binary-utils/releases/download/v0.1/php-7.1.3-Win32-VC14-x86.zip
    - 7z x php-7.1.3-Win32-VC14-x86.zip -y >nul
    - del /Q *.zip
    - cd ext
    - appveyor DownloadFile https://github.com/symfony/binary-utils/releases/download/v0.1/php_apcu-5.1.8-7.1-ts-vc14-x86.zip
    - 7z x php_apcu-5.1.8-7.1-ts-vc14-x86.zip -y >nul
    - del /Q *.zip
    - cd ..
    - gem install mailcatcher
    - copy /Y php.ini-development php.ini
    - echo max_execution_time=1200 >> php.ini
    - echo date.timezone="America/Sao_Paulo" >> php.ini
    - echo extension_dir=ext >> php.ini
    - echo zend_extension=php_opcache.dll >> php.ini
    - echo opcache.enable_cli=1 >> php.ini
    - echo extension=php_openssl.dll >> php.ini
    - echo extension=php_apcu.dll >> php.ini
    - echo apc.enable_cli=1 >> php.ini
    - echo extension=php_intl.dll >> php.ini
    - echo extension=php_mbstring.dll >> php.ini
    - echo extension=php_fileinfo.dll >> php.ini
    - echo extension=php_pdo_sqlite.dll >> php.ini
    - echo extension=php_curl.dll >> php.ini
    - echo extension=php_gd2.dll >> php.ini
    - echo curl.cainfo=c:\php\cacert.pem >> php.ini
    - cd c:\projects\chzapp
    - appveyor DownloadFile https://getcomposer.org/download/1.3.0/composer.phar
    - php composer.phar self-update
    - IF %APPVEYOR_REPO_BRANCH%==master (SET COMPOSER_ROOT_VERSION=dev-master) ELSE (SET COMPOSER_ROOT_VERSION=%APPVEYOR_REPO_BRANCH%.x-dev)
    - php composer.phar update --no-progress --ansi
    - SET COMPOSER_ROOT_VERSION=

before_test:
    - mysql -uroot -pPassword12! -e "CREATE USER 'chzapp'@'localhost' IDENTIFIED BY 'chzapp';"
    - mysql -uroot -pPassword12! -e "CREATE DATABASE chzapp;"
    - mysql -uroot -pPassword12! -e "GRANT SELECT ON chzapp.* TO 'chzapp'@'localhost';"
    - mailcatcher --smtp-port 1025

test_script:
    - cd c:\projects\chzapp
    - vendor/bin/phpunit
